# Generated by Django 4.2 on 2023-04-29 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_login_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
