# Generated by Django 4.2 on 2023-04-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_login_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=40)),
                ('confirm_password', models.EmailField(max_length=500)),
            ],
        ),
    ]
