# Generated by Django 4.2 on 2023-04-30 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='name',
        ),
    ]
