# Generated by Django 4.2 on 2023-05-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_username_signup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
